name: CI Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Gitleaks Scan
        uses: zricethezav/gitleaks-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Run Gitleaks with SARIF output
        run: |
          docker run --rm -v ${PWD}:/path zricethezav/gitleaks:latest detect --source="/path" --report-format=sarif --report-path=/path/gitleaks-results.sarif
          
      - name: Upload Gitleaks SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks-results.sarif
          category: gitleaks
        
      - name: Go Setup
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          
      - name: Build Test
        run: |
          go mod download
          go build -v ./...
        
      - name: Anchore Container Scan
        uses: anchore/scan-action@v5.3.0
        with:
          fail-build: false
          severity-cutoff: high
          output-format: sarif

      - name: Save Anchore scan results
        run: |
          cp ${{ steps.scan.outputs.sarif }} anchore-results.sarif
            
      - name: Upload Anchore scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: anchore-results.sarif
          category: anchore
      
      - name: Docker Build
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .
          docker tag ghcr.io/${{ github.repository }}:${{ github.sha }} ghcr.io/${{ github.repository }}:latest
      
      - name: GitHub Container Registry Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Docker Push
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}:latest